environment:
  # Nuxt requires node v12 minimum
  nodejs_version: '12'
  # Encrypt sensitive data (https://ci.appveyor.com/tools/encrypt)
  github_access_token:
    secure: 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
  github_email:
    secure: 237/CUTyCbNPhK2dow2eiozgVOx7IbUHIrlX3KwrU50=

# Only run on master branch
branches:
  only:
    - master

# Install scripts. (runs after repo cloning)
install:
  # switch nodejs version
  - ps: Install-Product node $env:12.16.3
  # install modules
  - npm install
  # generate static files
  - npm run generate
  # configure global git credentials store (https://www.appveyor.com/docs/how-to/git-push/)
  - git config --global credential.helper store
  - ps: Add-Content "$env:heesoo-pj\.git-credentials" "https://$($env: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):x-oauth-basic@github.com`n"
  - git config --global user.heesue1205@gmail.com $env:heesue1205@gmail.com
  # deploy to GitHub pages
  - npm run deploy

# No tests to run
test: off

# Don't actually build.
build: off
